import {
  ArrowRight,
  BadgeDollarSign,
  Binary,
  Blocks,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  ChartColumnBig,
  CircuitBoard,
  Coins,
  Factory,
  Handshake,
  HeartPulse,
  Landmark,
  Layers3,
  LockKeyhole,
  Mail,
  MapPinned,
  Phone,
  RefreshCw,
  Scale,
  ShieldCheck,
  ShoppingBag,
  Truck,
  UsersRound,
  WalletCards,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react';

export const iconMap = {
  arrowRight: ArrowRight,
  badgeDollarSign: BadgeDollarSign,
  binary: Binary,
  blocks: Blocks,
  bot: Bot,
  brainCircuit: BrainCircuit,
  briefcaseBusiness: BriefcaseBusiness,
  building2: Building2,
  chartColumnBig: ChartColumnBig,
  circuitBoard: CircuitBoard,
  coins: Coins,
  factory: Factory,
  handshake: Handshake,
  heartPulse: HeartPulse,
  landmark: Landmark,
  layers3: Layers3,
  lockKeyhole: LockKeyhole,
  mail: Mail,
  mapPinned: MapPinned,
  phone: Phone,
  refreshCw: RefreshCw,
  scale: Scale,
  shieldCheck: ShieldCheck,
  shoppingBag: ShoppingBag,
  truck: Truck,
  usersRound: UsersRound,
  walletCards: WalletCards,
  waypoints: Waypoints,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} as const;

export type SiteIconName = keyof typeof iconMap;
